services:
  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    env_file:
      - .env
    environment:
      - 'MYSQL_DATABASE=BANCO'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3306:3306'