CREATE DATABASE IF NOT EXISTS BANCO;

# PERSONA
CREATE TABLE IF NOT EXISTS BANCO.PERSONA(
    PERSONA_ID          BIGINT AUTO_INCREMENT,
    NOMBRE              VARCHAR(50) NOT NULL,
    GENERO              CHAR(1) NOT NULL,
    EDAD                INT(3) NOT NULL,
    IDENTIFICACION      VARCHAR(13) NOT NULL,
    DIRECCION           VARCHAR(150) NOT NULL,
    TELEFONO            VARCHAR(13) NOT NULL,
    CREADO              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT PERSONA_PK PRIMARY KEY (PERSONA_ID),
    CONSTRAINT PERSONA_CK1 CHECK (GENERO IN ('M', 'F'))
);

CREATE INDEX PERSONA_IX1 ON BANCO.PERSONA (IDENTIFICACION);


# CIENTE
CREATE TABLE IF NOT EXISTS BANCO.CLIENTE (
    CLIENTE_ID        BIGINT AUTO_INCREMENT,
    PERSONA_ID        BIGINT NOT NULL,
    USUARIO           VARCHAR(50) NOT NULL,
    CONTRASENIA       VARCHAR(50) NOT NULL,
    ESTADO            CHAR(1) NOT NULL,
    CREADO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT CLIENTE_CK1 CHECK (ESTADO IN ('A', 'I')),
    CONSTRAINT CLIENTE_FK1 FOREIGN KEY (PERSONA_ID)
        REFERENCES BANCO.PERSONA (PERSONA_ID)
);

CREATE UNIQUE INDEX CLIENTE_IX1 ON BANCO.CLIENTE (USUARIO);


# CUENTA
CREATE TABLE IF NOT EXISTS BANCO.CUENTA (
    CUENTA_ID         BIGINT AUTO_INCREMENT,
    CLIENTE_ID        BIGINT NOT NULL,
    NUMERO_CUENTA     VARCHAR(50) NOT NULL,
    TIPO_CUENTA       VARCHAR(50) NOT NULL,
    SALDO_INICIAL     DOUBLE NOT NULL,
    ESTADO            CHAR(1) NOT NULL,
    CREADO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT CUENTA_PK PRIMARY KEY (CUENTA_ID),
    CONSTRAINT CUENTA_CK1 CHECK (ESTADO IN ('A', 'I')),
    CONSTRAINT CUENTA_CK2 CHECK (TIPO_CUENTA IN ('C', 'A')),
    CONSTRAINT CUENTA_FK1 FOREIGN KEY (CLIENTE_ID)
        REFERENCES BANCO.CLIENTE (CLIENTE_ID)
);

CREATE UNIQUE INDEX CUENTA_IX1 ON BANCO.CUENTA (NUMERO_CUENTA);


# MOVIENTO
CREATE TABLE IF NOT EXISTS BANCO.MOVIMIENTO (
    MOVIMIENTO_ID         BIGINT AUTO_INCREMENT,
    CUENTA_ID             BIGINT NOT NULL,
    FECHA                 DATE NOT NULL,
    FECHA_PARTICION       DATE NOT NULL,  
    TIPO_MOVIMIENTO       CHAR(1) NOT NULL,
    VALOR                 DOUBLE NOT NULL,
    SALDO                 DOUBLE NOT NULL,
    CREADO                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTUALIZADO           TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT MOVIMIENTO_PK PRIMARY KEY (MOVIMIENTO_ID),
    CONSTRAINT MOVIMIENTO_CK1 CHECK (TIPO_MOVIMIENTO IN ('C', 'D')),
    CONSTRAINT MOVIMIENTO_FK1 FOREIGN KEY (CUENTA_ID)
        REFERENCES BANCO.CUENTA (CUENTA_ID)
);

CREATE INDEX MOVIMIENTO_IX1 ON BANCO.MOVIMIENTO (FECHA_PARTICION);
